config/routes.rb
Thirdplace::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'communities#index'
  get 'redirect' => 'application#redirect'
  get 'users/:id/people' => 'users#users', as: :user_users
  get 'communities/:id/people' => 'communities#users', as: :community_users
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:index, :show]
  resources :communities, only: [:index, :show]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/community.rb
class Community < ActiveRecord::Base
  has_many :community_users
  has_many :users, through: :community_users
end

app/models/community_types/company.rb
class Company < Community
end

app/models/community_types/degree.rb
class Degree < Community
end

app/models/community_types/field.rb
class Field < Community
end

app/models/community_types/gender.rb
class Gender < Community
end

app/models/community_types/school.rb
class School < Community
end

app/models/community_types/standing.rb
class Standing < Community
end

app/models/community_user.rb
class CommunityUser < ActiveRecord::Base
  belongs_to :community
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :community_users
  has_many :communities, through: :community_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def redirect
    redirect_to root_path
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  [Company, Degree, Field, Gender, School, Standing] if Rails.env == 'development'
  before_action :set_community, only: [:show, :users]

  def index
    @communities = Community.all
  end

  def show
  end

  def users
    # Randomness
    params[:seed] ||= Random.new_seed
    srand params[:seed].to_i

    # Users
    users = @community.users
    users = users.joins(:communities).where(communities: { id: params[:f] }).select("users.*, count(distinct(communities.id))").group("users.id").having("count(distinct(communities.id)) = (?)", params[:f].length) if params[:f]
    @users = Kaminari.paginate_array(users.shuffle).page(params[:page]).per(12)

    # Filters
    communities = Community.joins(:users).where(users: { id: @users.map(&:id) }).uniq.order(:name)
    @subclass_names = Community.subclasses.map(&:name)
    @subclass_names.each do |name|
      instance_variable_set("@#{name}_filters", communities.where(type: name).where.not(id: @community))
    end
  end

  private
    def set_community
      @community = Community.find(params[:id])
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    # required for settings form to submit when password is left blank
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end

    if resource.update_attributes(account_update_params)
      if is_navigational_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, :bypass => true
      respond_with resource, :location => after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  protected

  def account_update_params
    params.require(:user).permit(:name, :email, :image, :password, community_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  [Company, Degree, Field, Gender, School, Standing] if Rails.env == 'development'
  def index
    # Randomness
    params[:seed] ||= Random.new_seed
    srand params[:seed].to_i

    # Users
		users = User.all
    @users = Kaminari.paginate_array(users.shuffle).page(params[:page]).per(12)
  end

  def show
		@user = User.find(params[:id])
  end

  def users
    # Randomness
    params[:seed] ||= Random.new_seed
    srand params[:seed].to_i

    # Users
    users = User.joins(:communities).where(communities: { id: current_user.community_ids })
    users = users.where(communities: { id: params[:f] }).select("users.*, count(distinct(communities.id))").group("users.id").having("count(distinct(communities.id)) = (?)", params[:f].length) if params[:f]
    @users = Kaminari.paginate_array(users.shuffle).page(params[:page]).per(12)

    # Filters
    communities = Community.joins(:users).where(users: { id: @users.map(&:id) }).uniq.order(:name)
    @subclass_names = Community.subclasses.map(&:name)
    @subclass_names.each do |name|
      instance_variable_set("@#{name}_filters", communities.where(type: name))
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/communities/_tabs.html.slim
.tabs
  ul.container
    li
      = link_to root_path do
        i.fa.fa-bars
    li.active
      = link_to community_users_path(@community) do
        i.fa.fa-user
    / li
    /   = link_to root_path do
    /     i.fa.fa-circle-o

app/views/communities/_title.html.slim
.title
  ul.container
    li
      i.fa.fa-globe
      = @community.name

app/views/communities/index.html.slim
.container
  - @communities.each do |community|
    = link_to community_users_path(community) do
      .community
        = community.name

app/views/communities/users.html.slim
- content_for :javascript do
  = javascript_include_tag 'packery.min', 'imagesloaded.min', 'infinite_scroll.min', 'users'

= render 'title'
= render 'tabs'

.container
  .users-main
    .users
      = render @users
    #loading-users
    = paginate @users, remote: true
  .users-right
    .filters
      - @subclass_names.each do |name|
        - if instance_variable_get("@#{name}_filters").present?
          ul
            li.filters-title= name.capitalize
            - instance_variable_get("@#{name}_filters").each do |community|
              li class=("active-filter" if params[:f].try(:include?, community.id.to_s))
                = link_to url_for(params.merge(f: params[:f] ? params[:f].include?(community.id.to_s) ? params[:f] - [community.id.to_s] : params[:f] + [community.id.to_s] : [community.id.to_s])) do
                  - if params[:f].try(:include?, community.id.to_s)
                    i.fa.fa-times-circle
                  = community.name

app/views/layouts/_flash.html.slim
#flash
  p.notice= notice
  p.alert= alert

app/views/layouts/_header.html.slim
.header
  ul.container
    li.logo
      = link_to root_path do
        | thirdplace
    - if user_signed_in?
      li.home
        = link_to user_path(current_user) do
          i.fa.fa-home
      li.conversations
        = link_to root_path do
          i.fa.fa-comments-o
      li
        = link_to edit_user_registration_path do
          i.fa.fa-gear
    - else
      li.signup
        = link_to new_user_registration_path do
          i.fa.fa-asterisk
          | Sign Up
      li.login
        = link_to new_user_session_path do
          i.fa.fa-sign-in
          | Login

app/views/layouts/application.html.slim
doctype html
/ http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ]
  |<html class="ie6" lang="en">
/[if IE 7 ]
  |<html class="ie7" lang="en">
/[if IE 8 ]
  |<html class="ie8" lang="en">
/[if IE 9 ]
  |<html class="ie9" lang="en">
/[if (gt IE 9)|!(IE)]
  |<html lang="en">
head
  meta charset="utf-8"
  meta http-equiv="X-UA-Compatible" content="IE=7"
  meta name="viewport" content="width=device-width, initial-scale=1"
  meta name="description" content=""
  title == content_for?(:title) ? yield(:title) : "thirdplace"
  == stylesheet_link_tag "application", media: "all"
  == javascript_include_tag "//use.typekit.com/ier1ulg.js"
  == javascript_tag "try{Typekit.load()}catch(e){}"
  == csrf_meta_tags
body
  = render 'layouts/header'
  == yield
  / == debug(params) if Rails.env.development?
  == javascript_include_tag "application"
  == yield :javascript
|</html>

app/views/users/_profile.html.slim
.user-communities
  = user.communities.map { |community| "<div class='user-community'><i class='fa fa-caret-right'></i>" + community.name + "</div>"}.join(" ").html_safe
.user-actions
  = link_to root_path do
    | Introduce Yourself to #{user.name.split(" ")[0]}

app/views/users/_tabs.html.slim
.tabs
  ul.container
    li
      = link_to root_path do
        i.fa.fa-bars
    li.active
      = link_to user_users_path(current_user) do
        i.fa.fa-user
    / li
    /   = link_to root_path do
    /     i.fa.fa-circle-o

app/views/users/_user.html.slim
.user id=(user.id)
  = link_to user, remote: true do
    .user-card
      .user-image= image_tag user.image
      .user-name= user.name.split(" ")[0]
      .user-loading
        i.fa.fa-spinner.fa-spin
      .user-expand-icon
        i.fa.fa-angle-right
  .user-main

app/views/users/show.html.slim
.container
  h1 Users#show
  p Find me in app/views/users/show.html.slim
  = @user

app/views/users/show.js.erb
var $user = $('#<%= @user.id %>')
var $profile = $user.find(".user-main")
$user.toggleClass('is-expanded');
$user.find('.user-expand-icon i').toggleClass('fa-angle-right fa-angle-left');
if ($profile.html().length === 0) {
  $profile.html("<%= j render partial: 'profile', locals: { user: @user } %>");
}

app/views/users/users.html.slim
- content_for :javascript do
  = javascript_include_tag 'packery.min', 'imagesloaded.min', 'infinite_scroll.min', 'users'

= render 'users/tabs'

.container
  .users-main
    .users
      = render @users
    #loading-users
    = paginate @users, remote: true
  .users-right
    .filters
      - @subclass_names.each do |name|
        - if instance_variable_defined?("@#{name}_filters")
          ul
            li.filters-title= name.capitalize
            - instance_variable_get("@#{name}_filters").each do |community|
              li
                = link_to url_for(params.merge(f: params[:f] ? params[:f].include?(community.id.to_s) ? params[:f] - [community.id.to_s] : params[:f] + [community.id.to_s] : [community.id.to_s])) do
                  - if params[:f].try(:include?, community.id.to_s)
                    i.fa.fa-times-circle
                  = community.name